SELECT
        TO_CHAR(TO_NUMBER(SUBSTR(T8.PKSJ, 2, 2))) ||'-' ||TO_CHAR(TO_NUMBER(SUBSTR(T8.PKSJ, 4, 2))) ||'节' AS JC
FROM T_GXXS_BZKSJBXX T1
         LEFT JOIN DM_GB_XBM T2 ON T1.XBM=T2.DM
         LEFT JOIN T_GXXS_BZKSXJJBXX T3 ON T1.XH=T3.XH
         LEFT JOIN T_GXXX_BJJBXX T4 ON T3.XZBID=T4.BHID
         LEFT JOIN T_GXJX_BZKSXKXX T5 ON T3.XHID=T5.XH
         LEFT JOIN T_GXJX_BZKSKKXX T6 ON T5.TZDBH=T6.BIANH
         LEFT JOIN  T_GXJX_BZKSKCXX T7 ON T6.KCBH=T7.KCID
         LEFT JOIN T_GXJX_BKSJXAPB T10 ON T5.TZDBH=T10.TZDBH
         LEFT JOIN T_GXJX_BZKSKCAP  T9 ON T10.BIANH=T9.APBID
         LEFT JOIN T_GXJX_BKSPKXXXX T8 ON T10.BIANH=T8.APBID
         LEFT JOIN T_GXJG_JZGJBXX T11 ON T9.JSGH=T11.GH
         LEFT JOIN T_GXJX_BZKSKKHBXX T12 ON T5.HBBH=T12.BIANH
WHERE T3.SFZXM=1 AND T3.SFYXJM=1
