SELECT
    A.ASN AS WLKH,
    A.SCARDSNR AS YKTKH,
    '' AS YKTZHLX,
    A.OUTID AS "XH/ZGH",
    CASE WHEN STATUS=1 THEN '实体卡正常状态'
         WHEN STATUS=3 THEN '挂失'
         WHEN STATUS=4 THEN '冻结'
         WHEN STATUS=5 THEN '灰色'
         WHEN STATUS=6 THEN '停用'
         WHEN STATUS=97 THEN '虚拟卡正常状态'
         WHEN STATUS=99 THEN '未发卡'
         WHEN STATUS=-1 THEN '已注销'
        END AS ZHZT,
    A.NAME AS XM,
    A.ODDFARE AS STKZHYE,
    A.ONLINEODDFARE AS XNKKNYE,
    '' AS LJYKCS,
    CASE   WHEN  SEXNAME='男' THEN '1'
           WHEN  SEXNAME='女' THEN '2'
        END AS XBM,
    A.CUSTDEPT AS BMM,
    '' AS SFZLXM,
    A.IDCARDNO AS SFZJH,
    '' AS DH,
    '' AS YHZH,
    A.DOWNDT AS ZCRQ,
    A.NOUSEDATE AS GQRQ,
    '' AS ZHBZ,
    TO_CHAR(SYSDATE,'YYYY-MM-DD HH24:MI:SS') AS TSTAMP
FROM  T_YKT_M_BASE_CUSTOMERSCARD A
